
// File generated by FlutLab.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'try to add using FlutLab Firebase Configuration',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'it not supported by FlutLab yet, but you can add it manually',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeX18YPDnttQQVJ7_t0QYPuDPUhe7YIAo',
    authDomain: 'reflect-e337d.firebaseapp.com',
    projectId: 'reflect-e337d',
    storageBucket: 'reflect-e337d.firebasestorage.app',
    messagingSenderId: '886434462900',
    appId: '1:886434462900:web:96446ca97cdadca9adebe1',
    measurementId: 'G-YFZ8PH8K9R'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuk_MSdsCsH4KUhYVVuqw0ub4xuFI5YE0',
    appId: '1:886434462900:android:f231857759710966adebe1',
    messagingSenderId: '886434462900',
    projectId: 'reflect-e337d',
    storageBucket: 'reflect-e337d.firebasestorage.app'
  );
}
